# Generated by Django 5.0.3 on 2024-03-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendslist',
            name='user2',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='completed_count',
            new_name='crosses_completed',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='started_count',
            new_name='crosses_started',
        ),
        migrations.DeleteModel(
            name='FriendRequests',
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
