# Generated by Django 5.0.3 on 2024-04-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0003_remove_userdata_password_remove_userdata_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='current_cross',
            field=models.CharField(default='', max_length=244),
        ),
    ]
